'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DeviceEnabled() As Boolean
            Get
                Return CType(Me("DeviceEnabled"),Boolean)
            End Get
            Set
                Me("DeviceEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ColdResistanceCurrentLevelDefault() As Decimal
            Get
                Return CType(Me("ColdResistanceCurrentLevelDefault"),Decimal)
            End Get
            Set
                Me("ColdResistanceCurrentLevelDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0001")>  _
        Public Property ColdResistanceCurrentMinimum() As Decimal
            Get
                Return CType(Me("ColdResistanceCurrentMinimum"),Decimal)
            End Get
            Set
                Me("ColdResistanceCurrentMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0100")>  _
        Public Property ColdResistanceCurrentMaximum() As Decimal
            Get
                Return CType(Me("ColdResistanceCurrentMaximum"),Decimal)
            End Get
            Set
                Me("ColdResistanceCurrentMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property ColdResistanceVoltageLimitDefault() As Decimal
            Get
                Return CType(Me("ColdResistanceVoltageLimitDefault"),Decimal)
            End Get
            Set
                Me("ColdResistanceVoltageLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.10")>  _
        Public Property ColdResistanceVoltageMaximum() As Decimal
            Get
                Return CType(Me("ColdResistanceVoltageMaximum"),Decimal)
            End Get
            Set
                Me("ColdResistanceVoltageMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property ColdResistanceVoltageMinimum() As Decimal
            Get
                Return CType(Me("ColdResistanceVoltageMinimum"),Decimal)
            End Get
            Set
                Me("ColdResistanceVoltageMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.27")>  _
        Public Property ThermalTransientCurrentLevelDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientCurrentLevelDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientCurrentLevelDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.999")>  _
        Public Property ThermalTransientCurrentMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientCurrentMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientCurrentMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.099")>  _
        Public Property ThermalTransientVoltageChangeDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageChangeDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageChangeDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9.99")>  _
        Public Property ThermalTransientVoltageMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ThermalTransientVoltageMinimum() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageMinimum"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property PostTransientDelayDefault() As Decimal
            Get
                Return CType(Me("PostTransientDelayDefault"),Decimal)
            End Get
            Set
                Me("PostTransientDelayDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property PostTransientDelayMaximum() As Decimal
            Get
                Return CType(Me("PostTransientDelayMaximum"),Decimal)
            End Get
            Set
                Me("PostTransientDelayMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property PostTransientDelayMinimum() As Decimal
            Get
                Return CType(Me("PostTransientDelayMinimum"),Decimal)
            End Get
            Set
                Me("PostTransientDelayMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property ColdResistanceMinimum() As Decimal
            Get
                Return CType(Me("ColdResistanceMinimum"),Decimal)
            End Get
            Set
                Me("ColdResistanceMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ColdResistanceMaximum() As Decimal
            Get
                Return CType(Me("ColdResistanceMaximum"),Decimal)
            End Get
            Set
                Me("ColdResistanceMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.85")>  _
        Public Property ColdResistanceLowLimitDefault() As Decimal
            Get
                Return CType(Me("ColdResistanceLowLimitDefault"),Decimal)
            End Get
            Set
                Me("ColdResistanceLowLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2.156")>  _
        Public Property ColdResistanceHighLimitDefault() As Decimal
            Get
                Return CType(Me("ColdResistanceHighLimitDefault"),Decimal)
            End Get
            Set
                Me("ColdResistanceHighLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.006")>  _
        Public Property ThermalTransientLowLimitDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientLowLimitDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientLowLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.017")>  _
        Public Property ThermalTransientHighLimitDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientHighLimitDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientHighLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ColdResistanceApertureMinimum() As Decimal
            Get
                Return CType(Me("ColdResistanceApertureMinimum"),Decimal)
            End Get
            Set
                Me("ColdResistanceApertureMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ColdResistanceApertureMaximum() As Decimal
            Get
                Return CType(Me("ColdResistanceApertureMaximum"),Decimal)
            End Get
            Set
                Me("ColdResistanceApertureMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property ShuntResistanceApertureDefault() As Decimal
            Get
                Return CType(Me("ShuntResistanceApertureDefault"),Decimal)
            End Get
            Set
                Me("ShuntResistanceApertureDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ShuntResistanceApertureMinimum() As Decimal
            Get
                Return CType(Me("ShuntResistanceApertureMinimum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceApertureMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property ShuntResistanceApertureMaximum() As Decimal
            Get
                Return CType(Me("ShuntResistanceApertureMaximum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceApertureMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property ShuntResistanceCurrentLevelDefault() As Decimal
            Get
                Return CType(Me("ShuntResistanceCurrentLevelDefault"),Decimal)
            End Get
            Set
                Me("ShuntResistanceCurrentLevelDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00001")>  _
        Public Property ShuntResistanceCurrentMinimum() As Decimal
            Get
                Return CType(Me("ShuntResistanceCurrentMinimum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceCurrentMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.05")>  _
        Public Property ShuntResistanceCurrentMaximum() As Decimal
            Get
                Return CType(Me("ShuntResistanceCurrentMaximum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceCurrentMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ShuntResistanceCurrentRangeDefault() As Decimal
            Get
                Return CType(Me("ShuntResistanceCurrentRangeDefault"),Decimal)
            End Get
            Set
                Me("ShuntResistanceCurrentRangeDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ShuntResistanceVoltageLimitDefault() As Decimal
            Get
                Return CType(Me("ShuntResistanceVoltageLimitDefault"),Decimal)
            End Get
            Set
                Me("ShuntResistanceVoltageLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ShuntResistanceVoltageMinimum() As Decimal
            Get
                Return CType(Me("ShuntResistanceVoltageMinimum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceVoltageMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ShuntResistanceVoltageMaximum() As Decimal
            Get
                Return CType(Me("ShuntResistanceVoltageMaximum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceVoltageMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1150")>  _
        Public Property ShuntResistanceLowLimitDefault() As Decimal
            Get
                Return CType(Me("ShuntResistanceLowLimitDefault"),Decimal)
            End Get
            Set
                Me("ShuntResistanceLowLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1250")>  _
        Public Property ShuntResistanceHighLimitDefault() As Decimal
            Get
                Return CType(Me("ShuntResistanceHighLimitDefault"),Decimal)
            End Get
            Set
                Me("ShuntResistanceHighLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("900")>  _
        Public Property ShuntResistanceMinimum() As Decimal
            Get
                Return CType(Me("ShuntResistanceMinimum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
        Public Property ShuntResistanceMaximum() As Decimal
            Get
                Return CType(Me("ShuntResistanceMaximum"),Decimal)
            End Get
            Set
                Me("ShuntResistanceMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property ColdResistanceApertureDefault() As Decimal
            Get
                Return CType(Me("ColdResistanceApertureDefault"),Decimal)
            End Get
            Set
                Me("ColdResistanceApertureDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0001")>  _
        Public Property ThermalTransientSamplingIntervalDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientSamplingIntervalDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientSamplingIntervalDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00008")>  _
        Public Property ThermalTransientSamplingIntervalMinimum() As Decimal
            Get
                Return CType(Me("ThermalTransientSamplingIntervalMinimum"),Decimal)
            End Get
            Set
                Me("ThermalTransientSamplingIntervalMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property ThermalTransientSamplingIntervalMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientSamplingIntervalMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientSamplingIntervalMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("100")>  _
        Public Property ThermalTransientTracePointsDefault() As Integer
            Get
                Return CType(Me("ThermalTransientTracePointsDefault"),Integer)
            End Get
            Set
                Me("ThermalTransientTracePointsDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ThermalTransientTracePointsMinimum() As Integer
            Get
                Return CType(Me("ThermalTransientTracePointsMinimum"),Integer)
            End Get
            Set
                Me("ThermalTransientTracePointsMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ThermalTransientDurationDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientDurationDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientDurationDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ThermalTransientDurationMinimum() As Decimal
            Get
                Return CType(Me("ThermalTransientDurationMinimum"),Decimal)
            End Get
            Set
                Me("ThermalTransientDurationMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property ThermalTransientDurationMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientDurationMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientDurationMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.004")>  _
        Public Property ThermalTransientApertureDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientApertureDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientApertureDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property ThermalTransientApertureMinimum() As Decimal
            Get
                Return CType(Me("ThermalTransientApertureMinimum"),Decimal)
            End Get
            Set
                Me("ThermalTransientApertureMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ThermalTransientApertureMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientApertureMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientApertureMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
        Public Property ThermalTransientTracePointsMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientTracePointsMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientTracePointsMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ThermalTransientCurrentMinimum() As Decimal
            Get
                Return CType(Me("ThermalTransientCurrentMinimum"),Decimal)
            End Get
            Set
                Me("ThermalTransientCurrentMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ThermalTransientMedianFilterLengthDefault() As Integer
            Get
                Return CType(Me("ThermalTransientMedianFilterLengthDefault"),Integer)
            End Get
            Set
                Me("ThermalTransientMedianFilterLengthDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ThermalTransientMedianFilterLengthMinimum() As Decimal
            Get
                Return CType(Me("ThermalTransientMedianFilterLengthMinimum"),Decimal)
            End Get
            Set
                Me("ThermalTransientMedianFilterLengthMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property ThermalTransientMedianFilterLengthMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientMedianFilterLengthMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientMedianFilterLengthMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0005")>  _
        Public Property ThermalCoefficientDefault() As Decimal
            Get
                Return CType(Me("ThermalCoefficientDefault"),Decimal)
            End Get
            Set
                Me("ThermalCoefficientDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.00001")>  _
        Public Property ThermalCoefficientMinimum() As Decimal
            Get
                Return CType(Me("ThermalCoefficientMinimum"),Decimal)
            End Get
            Set
                Me("ThermalCoefficientMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property ThermalCoefficientMaximum() As Decimal
            Get
                Return CType(Me("ThermalCoefficientMaximum"),Decimal)
            End Get
            Set
                Me("ThermalCoefficientMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.99")>  _
        Public Property ThermalTransientVoltageLimitDefault() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageLimitDefault"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageLimitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.0")>  _
        Public Property ThermalTransientVoltageChangeMaximum() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageChangeMaximum"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageChangeMaximum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property ThermalTransientVoltageChangeMinimum() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageChangeMinimum"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageChangeMinimum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smua")>  _
        Public Property SourceMeasureUnitDefault() As String
            Get
                Return CType(Me("SourceMeasureUnitDefault"),String)
            End Get
            Set
                Me("SourceMeasureUnitDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ContactCheckEnabledDefault() As Boolean
            Get
                Return CType(Me("ContactCheckEnabledDefault"),Boolean)
            End Get
            Set
                Me("ContactCheckEnabledDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ContactCheckThresholdDefault() As Decimal
            Get
                Return CType(Me("ContactCheckThresholdDefault"),Decimal)
            End Get
            Set
                Me("ContactCheckThresholdDefault") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.5")>  _
        Public Property PostTransientDelay() As Decimal
            Get
                Return CType(Me("PostTransientDelay"),Decimal)
            End Get
            Set
                Me("PostTransientDelay") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ColdResistanceCurrentLevel() As Decimal
            Get
                Return CType(Me("ColdResistanceCurrentLevel"),Decimal)
            End Get
            Set
                Me("ColdResistanceCurrentLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.1")>  _
        Public Property ColdResistanceVoltageLimit() As Decimal
            Get
                Return CType(Me("ColdResistanceVoltageLimit"),Decimal)
            End Get
            Set
                Me("ColdResistanceVoltageLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.27")>  _
        Public Property ThermalTransientCurrentLevel() As Decimal
            Get
                Return CType(Me("ThermalTransientCurrentLevel"),Decimal)
            End Get
            Set
                Me("ThermalTransientCurrentLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.099")>  _
        Public Property ThermalTransientVoltageChange() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageChange"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageChange") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1.85")>  _
        Public Property ColdResistanceLowLimit() As Decimal
            Get
                Return CType(Me("ColdResistanceLowLimit"),Decimal)
            End Get
            Set
                Me("ColdResistanceLowLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2.156")>  _
        Public Property ColdResistanceHighLimit() As Decimal
            Get
                Return CType(Me("ColdResistanceHighLimit"),Decimal)
            End Get
            Set
                Me("ColdResistanceHighLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.006")>  _
        Public Property ThermalTransientLowLimit() As Decimal
            Get
                Return CType(Me("ThermalTransientLowLimit"),Decimal)
            End Get
            Set
                Me("ThermalTransientLowLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.017")>  _
        Public Property ThermalTransientHighLimit() As Decimal
            Get
                Return CType(Me("ThermalTransientHighLimit"),Decimal)
            End Get
            Set
                Me("ThermalTransientHighLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.99")>  _
        Public Property ThermalTransientVoltageLimit() As Decimal
            Get
                Return CType(Me("ThermalTransientVoltageLimit"),Decimal)
            End Get
            Set
                Me("ThermalTransientVoltageLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ContactCheckEnabled() As Boolean
            Get
                Return CType(Me("ContactCheckEnabled"),Boolean)
            End Get
            Set
                Me("ContactCheckEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ContactCheckThreshold() As Decimal
            Get
                Return CType(Me("ContactCheckThreshold"),Decimal)
            End Get
            Set
                Me("ContactCheckThreshold") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("GPIB0::26::INSTR")>  _
        Public Property ResourceName() As String
            Get
                Return CType(Me("ResourceName"),String)
            End Get
            Set
                Me("ResourceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.001")>  _
        Public Property ShuntResistanceCurrentLevel() As Decimal
            Get
                Return CType(Me("ShuntResistanceCurrentLevel"),Decimal)
            End Get
            Set
                Me("ShuntResistanceCurrentLevel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01")>  _
        Public Property ShuntResistanceCurrentRange() As Decimal
            Get
                Return CType(Me("ShuntResistanceCurrentRange"),Decimal)
            End Get
            Set
                Me("ShuntResistanceCurrentRange") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property ShuntResistanceVoltageLimit() As Decimal
            Get
                Return CType(Me("ShuntResistanceVoltageLimit"),Decimal)
            End Get
            Set
                Me("ShuntResistanceVoltageLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1150")>  _
        Public Property ShuntResistanceLowLimit() As Decimal
            Get
                Return CType(Me("ShuntResistanceLowLimit"),Decimal)
            End Get
            Set
                Me("ShuntResistanceLowLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1250")>  _
        Public Property ShuntResistanceHighLimit() As Decimal
            Get
                Return CType(Me("ShuntResistanceHighLimit"),Decimal)
            End Get
            Set
                Me("ShuntResistanceHighLimit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("..\measurements\Trace1.csv")>  _
        Public Property TraceFilePath() As String
            Get
                Return CType(Me("TraceFilePath"),String)
            End Get
            Set
                Me("TraceFilePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ftp://ttm%40isr.cc:ttm2.2@ftp.isr.cc")>  _
        Public ReadOnly Property FtpAddress() As String
            Get
                Return CType(Me("FtpAddress"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("..\measurements\Part1.csv")>  _
        Public Property PartsFilePath() As String
            Get
                Return CType(Me("PartsFilePath"),String)
            End Get
            Set
                Me("PartsFilePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Part 1")>  _
        Public Property PartNumber() As String
            Get
                Return CType(Me("PartNumber"),String)
            End Get
            Set
                Me("PartNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lot 1")>  _
        Public Property LotNumber() As String
            Get
                Return CType(Me("LotNumber"),String)
            End Get
            Set
                Me("LotNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Operator 1")>  _
        Public Property OperatorId() As String
            Get
                Return CType(Me("OperatorId"),String)
            End Get
            Set
                Me("OperatorId") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smua")>  _
        Public Property SourceMeasureUnit() As String
            Get
                Return CType(Me("SourceMeasureUnit"),String)
            End Get
            Set
                Me("SourceMeasureUnit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AutomaticallyAddPart() As Boolean
            Get
                Return CType(Me("AutomaticallyAddPart"),Boolean)
            End Get
            Set
                Me("AutomaticallyAddPart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Verbose")>  _
        Public Property TraceLevel() As Global.System.Diagnostics.TraceEventType
            Get
                Return CType(Me("TraceLevel"),Global.System.Diagnostics.TraceEventType)
            End Get
            Set
                Me("TraceLevel") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.isr.VI.Ttm.My.MySettings
            Get
                Return Global.isr.VI.Ttm.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
