'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("isr.VI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bmp101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmp101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bmp102() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmp102", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bmp103() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bmp103", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will clear all tests done on this lot.  Are you sure?.
        '''</summary>
        Friend ReadOnly Property str1001() As String
            Get
                Return ResourceManager.GetString("str1001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will complete testing on this lot.  Are you sure?.
        '''</summary>
        Friend ReadOnly Property str1002() As String
            Get
                Return ResourceManager.GetString("str1002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will complete testing on this lot item.  Are you sure?.
        '''</summary>
        Friend ReadOnly Property str1003() As String
            Get
                Return ResourceManager.GetString("str1003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will remove this lot item from the lot.  Are you sure?.
        '''</summary>
        Friend ReadOnly Property str1004() As String
            Get
                Return ResourceManager.GetString("str1004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will clear all tests done on this lot item from the lot.  Are you sure?.
        '''</summary>
        Friend ReadOnly Property str1005() As String
            Get
                Return ResourceManager.GetString("str1005", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This will retest this lot item clearing all previous tests.  Are you sure?.
        '''</summary>
        Friend ReadOnly Property str1006() As String
            Get
                Return ResourceManager.GetString("str1006", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Most likely the class specified below is not compatible with this application.  We suggest to install new class files from the original media for this application..
        '''</summary>
        Friend ReadOnly Property str101() As String
            Get
                Return ResourceManager.GetString("str101", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The program failed to locate the settings file: .
        '''</summary>
        Friend ReadOnly Property str102() As String
            Get
                Return ResourceManager.GetString("str102", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong case number..
        '''</summary>
        Friend ReadOnly Property str103() As String
            Get
                Return ResourceManager.GetString("str103", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program will resume after this message..
        '''</summary>
        Friend ReadOnly Property str104() As String
            Get
                Return ResourceManager.GetString("str104", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printer error.  Please correct and try again..
        '''</summary>
        Friend ReadOnly Property str105() As String
            Get
                Return ResourceManager.GetString("str105", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Most likely, either the printer isn&apos;t online -- physically switch the printer online, or the printer is jammed or out of paper -- physically correct the problem..
        '''</summary>
        Friend ReadOnly Property str106() As String
            Get
                Return ResourceManager.GetString("str106", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
