'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5.9.2008.0")>  _
        Public Property FoundationSystemFileVersion64() As String
            Get
                Return CType(Me("FoundationSystemFileVersion64"),String)
            End Get
            Set
                Me("FoundationSystemFileVersion64") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("17.5.0")>  _
        Public Property NationalInsrumentVisaVersion() As String
            Get
                Return CType(Me("NationalInsrumentVisaVersion"),String)
            End Get
            Set
                Me("NationalInsrumentVisaVersion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("INSTR")>  _
        Public Property DefaultResourceTitle() As String
            Get
                Return CType(Me("DefaultResourceTitle"),String)
            End Get
            Set
                Me("DefaultResourceTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<closed>")>  _
        Public Property DefaultClosedResourceCaption() As String
            Get
                Return CType(Me("DefaultClosedResourceCaption"),String)
            End Get
            Set
                Me("DefaultClosedResourceCaption") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("00:00:00.1000000")>  _
        Public Property SessionClosureRefractoryPeriod() As Global.System.TimeSpan
            Get
                Return CType(Me("SessionClosureRefractoryPeriod"),Global.System.TimeSpan)
            End Get
            Set
                Me("SessionClosureRefractoryPeriod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{0}.{1}")>  _
        Public Property DefaultOpenResourceTitleFormat() As String
            Get
                Return CType(Me("DefaultOpenResourceTitleFormat"),String)
            End Get
            Set
                Me("DefaultOpenResourceTitleFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{0}")>  _
        Public Property DefaultClosedResourceTitleFormat() As String
            Get
                Return CType(Me("DefaultClosedResourceTitleFormat"),String)
            End Get
            Set
                Me("DefaultClosedResourceTitleFormat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("17.5.0f0")>  _
        Public Property FoundationSystemFileVersion32() As String
            Get
                Return CType(Me("FoundationSystemFileVersion32"),String)
            End Get
            Set
                Me("FoundationSystemFileVersion32") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5.8.908.0")>  _
        Public Property FoundationVisaAssemblyVersion() As String
            Get
                Return CType(Me("FoundationVisaAssemblyVersion"),String)
            End Get
            Set
                Me("FoundationVisaAssemblyVersion") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.isr.VI.Pith.My.MySettings
            Get
                Return Global.isr.VI.Pith.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
