'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("isr.VI.E4990.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click OK to save the new compensation values or Cancel to ignore the new values..
        '''</summary>
        Friend ReadOnly Property FinishHelp() As String
            Get
                Return ResourceManager.GetString("FinishHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HeaderIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeaderIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the load resistance.  Connect a load resistance fixture at the Device Under Test terminals and click the Acquire button.  .
        '''</summary>
        Friend ReadOnly Property LoadHelp() As String
            Get
                Return ResourceManager.GetString("LoadHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect an open fixture at the Device Under Test terminals and click the Acquire button.  
        '''
        '''Acquiring new open values clears all compensations..
        '''</summary>
        Friend ReadOnly Property OpenHelp() As String
            Get
                Return ResourceManager.GetString("OpenHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the measurement speed (5) and averaging (16, enabled).  New values will be applied when moving Next..
        '''</summary>
        Friend ReadOnly Property SettingsHelp() As String
            Get
                Return ResourceManager.GetString("SettingsHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect a short fixture at the Device Under Test terminals and click the Acquire button.  
        '''.
        '''</summary>
        Friend ReadOnly Property ShortHelp() As String
            Get
                Return ResourceManager.GetString("ShortHelp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WelcomeImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WelcomeImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter the yardstick resistance values and accepted tolerance (%) and maximum inductance (micro Henry), connect a yardstick resistance fixture at the Device Under Test terminals and click the Measure button.  .
        '''</summary>
        Friend ReadOnly Property YardstickHelp() As String
            Get
                Return ResourceManager.GetString("YardstickHelp", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
